language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

before_script: |
  hg clone https://code.google.com/p/vim/
  cd vim
  ./configure --with-features=huge --enable-rubyinterp
  make
  sudo make install
  cd -

install: gem install rspec

script: rspec spec
